server_url: http://server:8000/ping-mesh # Server URL
#interval: 60s # Ticker interval time
#log_level: info #Log level
#ping:
  #count: 1 # Ping count
  #interval: 1s # Ping interval time
  #timeout: 5s # Ping timeout time

hosts:
  - name: router # Ping target hostname
    host: 10.0.0.1 # Ping target host (FQDN or IP Addres)
